---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-devops
spec:
  selector:
    matchLabels:
      app: ic-devops
  replicas: 1
  template:
    metadata:
      labels:
        app: ic-devops
    spec:
      volumes:
      - name: ic-volume-devops
        emptyDir: {}
      containers:
      - name: ic-main-devops
        image: centos:latest
        command: ['/bin/bash', '-c', ''while true; do cat /ic/official; sleep 5; done'']
        volumeMounts:
        - name: ic-volume-devops
          mountPath: /ic
      initContainers:
      - name: ic-msg-devops
        image: centos:latest
        command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/official']
        volumeMounts:
        - name: ic-volume-devops
          mountPath: /ic
