---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drupal-mysql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1 
kind: Deployment            
metadata:
  name: drupal-mysql       
  labels:                       
    app: drupal-mysql 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  strategy:
    type: Recreate
  template:                    
    metadata:
      labels:                  
        app: drupal-mysql
    spec:                       
      containers: 
      - image: mysql:5.7 
        name: mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef: 
              name: mysql-root-pass 
              key: password 
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef: 
              name: mysql-db-url 
              key: database 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306        
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:                       
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
stringData:
  password: YUIidhb667
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
stringData:
  username: kodekloud_sam
  password: BruCStnMT5
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: Opaque
stringData:
  database: kodekloud_db1
---
apiVersion: apps/v1 
kind: Deployment            
metadata:
  name: drupal     
  labels:                       
    app: drupal 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: Recreate
  template:                    
    metadata:
      labels:                  
        app: drupal
    spec:                       
      containers: 
      - image: drupal:8.6 
        name: drupal
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef: 
              name: mysql-root-pass 
              key: password 
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef: 
              name: mysql-db-url 
              key: database 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
---
apiVersion: v1                    
kind: Service                      
metadata:
  name: drupal-mysql-service         
  labels:             
    app: drupal-mysql
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:    
    app: drupal-mysql
---
apiVersion: v1                    
kind: Service                      
metadata:
  name: drupal-service
  labels:             
    app: drupal
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30095
  selector:    
    app: drupal
