apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset-t3q4
  labels:
    front-end-t3q4: httpd_app_t3q4
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      front-end-t3q4: httpd_app_t3q4
  template:
    metadata:
      labels:
        front-end-t3q4: httpd_app_t3q4
    spec:
      containers:
      - name: httpd-container-t3q4
        image: httpd:latest
