---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  # property-like keys; each key maps to a simple value
  variables_order: "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  type: Opaque
stringData:
  mysql_root_password: super_password
  mysql_database: db1
  mysql_user: user1
  mysql_password: pass1
  mysql_host: host1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  selector:
    matchLabels:
      app: lamp-wp
  replicas: 1
  template:
    metadata:
      labels:
        app: lamp-wp
    spec:
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_host
      - name: mysql-container
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_host
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  selector:
    app: lamp-wp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp-wp
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
