---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 8093;
        root /var/www/html;
        location / {
        root   /var/www/html;
        index  index.html index.htm index.php;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  namespace: default
  labels:
    app: php-fpm
spec:
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: shared-files
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-files
    - mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
      name: nginx-config-volume
  - name: php-fpm-container
    image: php:8.1-fpm-alpine
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-files
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  type: NodePort
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
      nodePort: 30012
